[package]
name = "virtual-actor-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0"
quote = "1.0"
uuid = { version = "1.5.0", features = ["v4", "fast-rng"] }